# -*- coding: utf-8 -*- #
# frozen_string_literal: true

require 'nokogiri'
require_relative "../task_helper"
require 'pry'

IGOR_PRO_KEYWORDS_FILE = "./lib/rouge/lexers/igorpro/builtins.rb"

namespace :builtins do
  task :igorpro do
    IgorProBuiltins.process(IGOR_PRO_KEYWORDS_FILE)
  end
end

class IgorProBuiltins < BuiltinsGenerator
  def fetch
    URI.open('https://docs.wavemetrics.com/igorpro/commands')
  end

  def parse
    doc = Nokogiri.HTML(@input)

    operations = []
    functions = []

    nodes = doc.xpath('//span[starts-with(@class, "commandType")]').each do |type|
      root = type.parent

      name = root.xpath('span[starts-with(@class, "commandName")]')

      raise "something went wrong, check igorpro.rake" unless name.size == 1

      name = name[0]

      case type.text
      when "operation"
        operations << name.text.downcase
      when "function"
        functions << name.text.downcase
      end
    end

    operations.sort!
    operations.uniq!

    functions.sort!
    functions.uniq!

    # ensure disjoint
    operations -= functions

    { operations: operations, functions: functions }
  end

  def generate
    yield "# -*- coding: utf-8 -*- #"
    yield "# frozen_string_literal: true"
    yield ""
    yield "# DO NOT EDIT"
    yield "# This file is automatically generated by `rake builtins:igorpro`."
    yield "# See tasks/builtins/igorpro.rake for more info."
    yield ""
    yield "module Rouge"
    yield "  module Lexers"
    yield "    class IgorPro"
    yield "      FUNCTIONS = Set#{@keywords[:functions].inspect}"
    yield "      OPERATIONS = Set#{@keywords[:operations].inspect}"
    yield "    end"
    yield "  end"
    yield "end"
  end
end
