inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - "tasks/**/*"
    - "vendor/**/*"

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Bundler:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false
