# -*- coding: utf-8 -*- #
# frozen_string_literal: true

# DO NOT EDIT
# This file is automatically generated by `rake builtins:davi`.
# See tasks/builtins/davi.rake for more info.

module Rouge
  module Lexers
    class DAVI
      def self.builtins
        @builtins ||= {}.tap do |b|
          b["Array"] = Set.new ["append", "range", "slice", "sort"]
          b["Conversion"] = Set.new ["int", "str"]
          b["File System"] = Set.new ["fileGetContents"]
          b["HTTP"] = Set.new ["httpListen", "httpRegister"]
          b["String"] = Set.new ["camelCase", "char", "dotCase", "explode", "find", "join", "kebabCase", "len", "lower", "lowerFirst", "lowerWords", "pascalCase", "rune", "snakeCase", "split", "type", "upFirst", "upWords", "upper"]
          b["System"] = Set.new ["args", "echo", "exit", "read", "time"]
        end
      end
    end
  end
end