# -*- coding: utf-8 -*- #
# frozen_string_literal: true

# DO NOT EDIT
# This file is automatically generated by `rake builtins:davi`.
# See tasks/builtins/davi.rake for more info.

module Rouge
  module Lexers
    class DAVI
      def self.builtins
        @builtins ||= {}.tap do |b|
          b["Array"] = Set.new ["array_change_key_case", "array_chunk", "array_column", "array_combine", "array_count_values", "array_diff_assoc", "array_diff_key", "array_diff_uassoc", "array_diff_ukey", "array_diff", "array_fill_keys", "array_fill", "array_filter", "array_flip", "array_intersect_assoc", "array_intersect_key", "array_intersect_uassoc", "array_intersect_ukey", "array_intersect", "array_key_exists", "array_key_first", "array_key_last", "array_keys", "array_map", "array_merge_recursive", "array_merge", "array_multisort", "array_pad", "array_pop", "array_product", "array_push", "array_rand", "array_reduce", "array_replace_recursive", "array_replace", "array_reverse", "array_search", "array_shift", "array_slice", "array_splice", "array_sum", "array_udiff_assoc", "array_udiff_uassoc", "array_udiff", "array_uintersect_assoc", "array_uintersect_uassoc", "array_uintersect", "array_unique", "array_unshift", "array_values", "array_walk_recursive", "array_walk", "array", "arsort", "asort", "compact", "count", "current", "each", "end", "extract", "in_array", "key_exists", "key", "krsort", "ksort", "list", "natcasesort", "natsort", "next", "pos", "prev", "range", "reset", "rsort", "shuffle", "sizeof", "sort", "uasort", "uksort", "usort"]
          b["Array"] = Set.new ["append", "range", "slice", "sort"]
          b["Conversion"] = Set.new ["int", "str"]
          b["File System"] = Set.new ["fileGetContents"]
          b["HTTP"] = Set.new ["httpListen", "httpRegister"]
          b["String"] = Set.new ["camelCase", "char", "dotCase", "explode", "find", "join", "kebabCase", "len", "lower", "lowerFirst", "lowerWords", "pascalCase", "rune", "snakeCase", "split", "type", "upFirst", "upWords", "upper"]
          b["System"] = Set.new ["args", "echo", "exit", "read", "time"]
        end
      end
    end
  end
end