# -*- coding: utf-8 -*- #
# frozen_string_literal: true

describe Rouge::Lexers::Ion do
  let(:subject) { Rouge::Lexers::Ion.new }

  describe 'guessing' do
    include Support::Guessing

    it 'guesses by filename' do
      assert_guess :filename => 'file.ion'
    end

    it 'guesses by mimetype' do
      assert_guess :mimetype => 'application/ion'
    end
  end

  describe 'lexing' do
    include Support::Lexing

    it 'handles a basic file' do
      ion = <<~ION
        /**
         * comment
         */
        'annotation' :: {
          a: 1,
          'b': 2.0,
          "c": float:: 1.23e-4,
          "d": 'null':: null.symbol,
          "e": 'timestamps':: [
            1970-01-01T00:00Z,
            1970T,
          ],
          f: 'constants and such':: [
            nancy, nan,
            "+infinity", +inf, -inf,
            truee, false, true,
            null.null, null,
            nullish,
          ],
          "g": (add [0b101, 0xdeadbeef, -1_000] "hello"),
          h: { i: '''string''', },
          j: {{ aW9u }},
        }
      ION

      assert_no_errors ion

      assert_tokens_equal ion,
        ["Comment.Multiline", "/**\n * comment\n */"],
        ["Text.Whitespace", "\n"],
        ["Name.Decorator", "'annotation'"],
        ["Text.Whitespace", " "],
        ["Operator", "::"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "{"],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "a"],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Literal.Number.Integer", "1"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "'b'"],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Literal.Number.Float", "2.0"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "\"c\""],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Name.Decorator", "float"],
        ["Operator", "::"],
        ["Text.Whitespace", " "],
        ["Literal.Number.Float", "1.23e-4"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "\"d\""],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Name.Decorator", "'null'"],
        ["Operator", "::"],
        ["Text.Whitespace", " "],
        ["Name.Builtin", "null.symbol"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "\"e\""],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Name.Decorator", "'timestamps'"],
        ["Operator", "::"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "["],
        ["Text.Whitespace", "\n    "],
        ["Literal.Date", "1970-01-01T00:00Z"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n    "],
        ["Literal.Date", "1970T"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Punctuation.Indicator", "]"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "f"],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Name.Decorator", "'constants and such'"],
        ["Operator", "::"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "["],
        ["Text.Whitespace", "\n    "],
        ["Literal.String.Symbol", "nancy"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Literal.Number.Float", "nan"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n    "],
        ["Literal.String.Double", "\"+infinity\""],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Literal.Number.Float", "+inf"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Literal.Number.Float", "-inf"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n    "],
        ["Literal.String.Symbol", "truee"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Name.Builtin", "false"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Name.Builtin", "true"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n    "],
        ["Name.Builtin", "null.null"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Name.Builtin", "null"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n    "],
        ["Literal.String.Symbol", "nullish"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Punctuation.Indicator", "]"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "\"g\""],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "("],
        ["Literal.String.Symbol", "add"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "["],
        ["Literal.Number.Bin", "0b101"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Literal.Number.Hex", "0xdeadbeef"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Literal.Number.Integer", "-1_000"],
        ["Punctuation.Indicator", "]"],
        ["Text.Whitespace", " "],
        ["Literal.String.Double", "\"hello\""],
        ["Punctuation.Indicator", ")"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "h"],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "{"],
        ["Text.Whitespace", " "],
        ["Name.Label", "i"],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Literal.String.Double", "'''string'''"],
        ["Punctuation", ","],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "}"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n  "],
        ["Name.Label", "j"],
        ["Punctuation", ":"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "{{"],
        ["Text.Whitespace", " "],
        ["Literal", "aW9u"],
        ["Text.Whitespace", " "],
        ["Punctuation.Indicator", "}}"],
        ["Punctuation", ","],
        ["Text.Whitespace", "\n"],
        ["Punctuation.Indicator", "}"],
        ["Text.Whitespace", "\n"]
    end
  end
end
