# -*- coding: utf-8 -*- #
# frozen_string_literal: true

# DO NOT EDIT

# This file is automatically generated by `rake keywords:scilab`.
# See tasks/builtins/scilab.rake for more info.

module Rouge
  module Lexers
    def Scilab.keywords
      @keywords ||= Set.new ["abort", "apropos", "break", "case", "catch", "clc", "clear", "continue", "do", "else", "elseif", "end", "endfunction", "exit", "for", "function", "help", "if", "pause", "pwd", "quit", "resume", "return", "select", "then", "try", "what", "while", "who"]
    end
  end
end
