---
name: CI

on:
  push:
    # The `github-workflow-test` can be used to test changes without making a PR
    branches: [master, github-workflow-test]
  pull_request:
    branches: [master]

jobs:
  linelint:
    name: Linelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fernandrone/linelint@master

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rake check:style

  test:
    name: Test ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1", "3.2", "3.3"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake check:specs

  profile:
    name: Profile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Profile Memory Allocation
        run: bundle exec rake check:memory
      - name: Interpreter Warnings Test
        env:
          RUBYOPT: "-w"
        run: bundle exec rake check:specs
